### PR TITLE
Major rework

### PR DESCRIPTION
**Pull request by itimpi**
- Re-ordered file to make it easier to maintain.
- Lots of new text strings to support latest plugin changes

### CODE REVIEW

**Comment by spencerjunraid** [comment]
@Squidly271 - Just double checking that this won't run into any issues with other repos? TIA

**Comment by itimpi** [comment]
Not quite sure what you mean.    I think that the majority of the strings have either changed or are new so any other languages are going to need significant work to support the latest version of the parity.check.tuning plugin

**Comment by spencerjunraid** [comment]
Hey @itimpi, thanks! I think you are correct, but just wanted a second set of eyes on it. Will merge...

**Comment by Squidly271** [comment]
There's no problems with conflicts on any other plugins / the OS.

**Pull request merged**
