### PR TITLE
Updates to align translations with latest Parity Check Tuning (version 2021-04-02)

### PR DESCRIPTION
**Pull request by itimpi**
updates for compatibility with latest version of Parity Check Tuning plugin

### CODE REVIEW

**Comment by roquint** [comment]
hello itimpi and thanks for your great work on this plugin, i was translating in french the file lang-en_US/Parity Check Tuning/paritychecktuning.txt and i noticed some issues on this file, i've reported all the issues in the main repo here, please check it when you can, i'm waiting your corrections to finish translations :
[https://github.com/unraid/lang-en_US/issues](https://github.com/unraid/lang-en_US/issues)

**Comment by itimpi** [comment]
Roland,

I have pushed updates that I think will fix all the issues you mentioned.  I have left the issues open so when you have checked if the fixes work please close them.   Unfortunately I had to make more changes than just those raised by your issues to fix things I noticed while looking at the ones you raised and I hope these do not cause you too much extra work.

As a point of reference I would also be happy if you want to raise any similar issues directly against my plugin project on GitHub as that is where all fixes are initially done and only later copied across to the translations project run by Limetech.  I am more likely to rapidly notice issues raised there.

Dave Walker

Sent from my iPad Pro
Tel: 01707 652791
Mobile: 07305 354506

**Comment by roquint** [comment]
Hi dave,  No problem for the extra work, it can happen it’s a normal thing in every open source project, i ‘ve tried to raise an issue on your repo but i cannot, when for example, when i click on a line on the file :lang-en_US/Parity Check Tuning/paritychecktuning.txt i’ve no option to raise an issue, i only have :Copy lineCopy permalinkView git blame I’m not very used to GitHub, perhaps i’ve missed Something… or have you a setting to allow raising errors on your git ? Ps : i also make some mistakes sometime, i’m french, English is not my primary language. Have a nice day   Provenance : Courrier pour Windows 10 De : itimpiEnvoyé le :mardi 13 avril 2021 17:43À : unraid/lang-en_USCc : Roland Quintin; CommentObjet :Re: [unraid/lang-en_US] Updates to align translations with latest Parity Check Tuning (version 2021-04-02) (#61) Roland,I have pushed updates that I think will fix all the issues you mentioned. I have left the issues open so when you have checked if the fixes work please close them. Unfortunately I had to make more changes than just those raised by your issues to fix things I noticed while looking at the ones you raised and I hope these do not cause you too much extra work.As a point of reference I would also be happy if you want to raise any similar issues directly against my plugin project on GitHub as that is where all fixes are initially done and only later copied across to the translations project run by Limetech. I am more likely to rapidly notice issues raised there.Dave WalkerSent from my iPad ProTel: 01707 652791Mobile: 07305 354506> On 12 Apr 2021, at 22:41, Roland Quintin ***@***.***> wrote:> > ﻿> hello itimpi and thanks for your great work on this plugin, i was translating in french the file lang-en_US/Parity Check Tuning/paritychecktuning.txt and i noticed some issues on this file, i've reported all the issues in the main repo here, please check it when you can, i'm waiting your corrections to finish translations :> https://github.com/unraid/lang-en_US/issues> > —> You are receiving this because you authored the thread.> Reply to this email directly, view it on GitHub, or unsubscribe.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by itimpi** [comment]
I was suggesting that you raise the issue on the Parity Check Tuning plugin where you should see an Issues button available.    There will also be a copy of the translations file in that project and it is often ahead of the one under the lang-en_US project in my repositories as I update that version whenever I update the plugin as it is important the translations file is kept in-step with the plugin code.    I then periodically copy the latest version of the translations file across to my local lang-en_US project ready to be submitted to the Limetech version of that project.

Dave Walker

Sent from my iPad Pro
Tel: 01707 652791
Mobile: 07305 354506

**Comment by roquint** [comment]
Thanks, i’ve found it Provenance : Courrier pour Windows 10 De : itimpiEnvoyé le :mercredi 14 avril 2021 12:06À : unraid/lang-en_USCc : Roland Quintin; CommentObjet :Re: [unraid/lang-en_US] Updates to align translations with latest Parity Check Tuning (version 2021-04-02) (#61) I was suggesting that you raise the issue on the Parity Check Tuning plugin where you should see an Issues button available. There will also be a copy of the translations file in that project and it is often ahead of the one under the lang-en_US project in my repositories as I update that version whenever I update the plugin as it is important the translations file is kept in-step with the plugin code. I then periodically copy the latest version of the translations file across to my local lang-en_US project ready to be submitted to the Limetech version of that project.Dave WalkerSent from my iPad ProTel: 01707 652791Mobile: 07305 354506> On 13 Apr 2021, at 21:57, Roland Quintin ***@***.***> wrote:> > ﻿> Hi dave, No problem for the extra work, it can happen it’s a normal thing in every open source project, i ‘ve tried to raise an issue on your repo but i cannot, when for example, when i click on a line on the file :lang-en_US/Parity Check Tuning/paritychecktuning.txt i’ve no option to raise an issue, i only have :Copy lineCopy permalinkView git blame I’m not very used to GitHub, perhaps i’ve missed Something… or have you a setting to allow raising errors on your git ? Ps : i also make some mistakes sometime, i’m french, English is not my primary language. Have a nice day Provenance : Courrier pour Windows 10 De : itimpiEnvoyé le :mardi 13 avril 2021 17:43À : unraid/lang-en_USCc : Roland Quintin; CommentObjet :Re: [unraid/lang-en_US] Updates to align translations with latest Parity Check Tuning (version 2021-04-02) (#61) Roland,I have pushed updates that I think will fix all the issues you mentioned. I have left the issues open so when you have checked if the fixes work please close them. Unfortunately I had to make more changes than just those raised by your issues to fix things I noticed while looking at the ones you raised and I hope these do not cause you too much extra work.As a point of reference I would also be happy if you want to raise any similar issues directly against my plugin project on GitHub as that is where all fixes are initially done and only later copied across to the translations project run by Limetech. I am more likely to rapidly notice issues raised there.Dave WalkerSent from my iPad ProTel: 01707 652791Mobile: 07305 354506> On 12 Apr 2021, at 22:41, Roland Quintin ***@***.***> wrote:> > ﻿> hello itimpi and thanks for your great work on this plugin, i was translating in french the file lang-en_US/Parity Check Tuning/paritychecktuning.txt and i noticed some issues on this file, i've reported all the issues in the main repo here, please check it when you can, i'm waiting your corrections to finish translations :> https://github.com/unraid/lang-en_US/issues> > —> You are receiving this because you authored the thread.> Reply to this email directly, view it on GitHub, or unsubscribe.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. > —> You are receiving this because you authored the thread.> Reply to this email directly, view it on GitHub, or unsubscribe.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
